/*
 * File: dspc_pid.c
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand,
 *   you must change it only in the area defined as:
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text'
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Simulink Coder, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Simulink Coder's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  -------------------------------------------------------------------------
 *
 * Created: Tue Jun 14 14:41:18 2022
 */

#define S_FUNCTION_LEVEL               2
#define S_FUNCTION_NAME                dspc_pid

/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS                     1

/* Input Port  0 */
#define IN_PORT_0_NAME                 u
#define INPUT_0_WIDTH                  1
#define INPUT_DIMS_0_COL               1
#define INPUT_0_DTYPE                  real32_T
#define INPUT_0_COMPLEX                COMPLEX_NO
#define IN_0_FRAME_BASED               FRAME_NO
#define IN_0_BUS_BASED                 0
#define IN_0_BUS_NAME
#define IN_0_DIMS                      1-D
#define INPUT_0_FEEDTHROUGH            1
#define IN_0_ISSIGNED                  0
#define IN_0_WORDLENGTH                8
#define IN_0_FIXPOINTSCALING           1
#define IN_0_FRACTIONLENGTH            9
#define IN_0_BIAS                      0
#define IN_0_SLOPE                     0.125
#define NUM_OUTPUTS                    3

/* Output Port  0 */
#define OUT_PORT_0_NAME                y
#define OUTPUT_0_WIDTH                 1
#define OUTPUT_DIMS_0_COL              1
#define OUTPUT_0_DTYPE                 real32_T
#define OUTPUT_0_COMPLEX               COMPLEX_NO
#define OUT_0_FRAME_BASED              FRAME_NO
#define OUT_0_BUS_BASED                0
#define OUT_0_BUS_NAME
#define OUT_0_DIMS                     1-D
#define OUT_0_ISSIGNED                 1
#define OUT_0_WORDLENGTH               8
#define OUT_0_FIXPOINTSCALING          1
#define OUT_0_FRACTIONLENGTH           3
#define OUT_0_BIAS                     0
#define OUT_0_SLOPE                    0.125

/* Output Port  1 */
#define OUT_PORT_1_NAME                pidsum
#define OUTPUT_1_WIDTH                 1
#define OUTPUT_DIMS_1_COL              1
#define OUTPUT_1_DTYPE                 real32_T
#define OUTPUT_1_COMPLEX               COMPLEX_NO
#define OUT_1_FRAME_BASED              FRAME_NO
#define OUT_1_BUS_BASED                0
#define OUT_1_BUS_NAME
#define OUT_1_DIMS                     1-D
#define OUT_1_ISSIGNED                 1
#define OUT_1_WORDLENGTH               8
#define OUT_1_FIXPOINTSCALING          1
#define OUT_1_FRACTIONLENGTH           3
#define OUT_1_BIAS                     0
#define OUT_1_SLOPE                    0.125

/* Output Port  2 */
#define OUT_PORT_2_NAME                Xi
#define OUTPUT_2_WIDTH                 1
#define OUTPUT_DIMS_2_COL              1
#define OUTPUT_2_DTYPE                 real32_T
#define OUTPUT_2_COMPLEX               COMPLEX_NO
#define OUT_2_FRAME_BASED              FRAME_NO
#define OUT_2_BUS_BASED                0
#define OUT_2_BUS_NAME
#define OUT_2_DIMS                     1-D
#define OUT_2_ISSIGNED                 1
#define OUT_2_WORDLENGTH               8
#define OUT_2_FIXPOINTSCALING          1
#define OUT_2_FRACTIONLENGTH           3
#define OUT_2_BIAS                     0
#define OUT_2_SLOPE                    0.125
#define NPARAMS                        15

/* Parameter 0 */
#define PARAMETER_0_NAME               Ts
#define PARAMETER_0_DTYPE              real32_T
#define PARAMETER_0_COMPLEX            COMPLEX_NO

/* Parameter 1 */
#define PARAMETER_1_NAME               Kp
#define PARAMETER_1_DTYPE              real32_T
#define PARAMETER_1_COMPLEX            COMPLEX_NO

/* Parameter 2 */
#define PARAMETER_2_NAME               Ki
#define PARAMETER_2_DTYPE              real32_T
#define PARAMETER_2_COMPLEX            COMPLEX_NO

/* Parameter 3 */
#define PARAMETER_3_NAME               Kd
#define PARAMETER_3_DTYPE              real32_T
#define PARAMETER_3_COMPLEX            COMPLEX_NO

/* Parameter 4 */
#define PARAMETER_4_NAME               N
#define PARAMETER_4_DTYPE              real32_T
#define PARAMETER_4_COMPLEX            COMPLEX_NO

/* Parameter 5 */
#define PARAMETER_5_NAME               limit_output
#define PARAMETER_5_DTYPE              boolean_T
#define PARAMETER_5_COMPLEX            COMPLEX_NO

/* Parameter 6 */
#define PARAMETER_6_NAME               upper_limit
#define PARAMETER_6_DTYPE              real32_T
#define PARAMETER_6_COMPLEX            COMPLEX_NO

/* Parameter 7 */
#define PARAMETER_7_NAME               lower_limit
#define PARAMETER_7_DTYPE              real32_T
#define PARAMETER_7_COMPLEX            COMPLEX_NO

/* Parameter 8 */
#define PARAMETER_8_NAME               limit_rate
#define PARAMETER_8_DTYPE              boolean_T
#define PARAMETER_8_COMPLEX            COMPLEX_NO

/* Parameter 9 */
#define PARAMETER_9_NAME               rising_slew_rate
#define PARAMETER_9_DTYPE              real32_T
#define PARAMETER_9_COMPLEX            COMPLEX_NO

/* Parameter 10 */
#define PARAMETER_10_NAME              falling_slew_rate
#define PARAMETER_10_DTYPE             real32_T
#define PARAMETER_10_COMPLEX           COMPLEX_NO

/* Parameter 11 */
#define PARAMETER_11_NAME              anti_windup_enabled
#define PARAMETER_11_DTYPE             boolean_T
#define PARAMETER_11_COMPLEX           COMPLEX_NO

/* Parameter 12 */
#define PARAMETER_12_NAME              Kb
#define PARAMETER_12_DTYPE             real32_T
#define PARAMETER_12_COMPLEX           COMPLEX_NO

/* Parameter 13 */
#define PARAMETER_13_NAME              tracking_enabled
#define PARAMETER_13_DTYPE             boolean_T
#define PARAMETER_13_COMPLEX           COMPLEX_NO

/* Parameter 14 */
#define PARAMETER_14_NAME              Kt
#define PARAMETER_14_DTYPE             real32_T
#define PARAMETER_14_COMPLEX           COMPLEX_NO
#define SAMPLE_TIME_0                  0.1
#define NUM_DISC_STATES                0
#define DISC_STATES_IC                 [0]
#define NUM_CONT_STATES                0
#define CONT_STATES_IC                 [0]
#define SFUNWIZ_GENERATE_TLC           0
#define SOURCEFILES                    "__SFB__LIB_PATH ..\build\DSP__SFB__INC_PATH ..\DSP\include__SFB__libDSPc.lib"
#define PANELINDEX                     N/A
#define USE_SIMSTRUCT                  0
#define SHOW_COMPILE_STEPS             0
#define CREATE_DEBUG_MEXFILE           0
#define SAVE_CODE_ONLY                 1
#define SFUNWIZ_REVISION               3.0

/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"
#define PARAM_DEF0(S)                  ssGetSFcnParam(S, 0)
#define PARAM_DEF1(S)                  ssGetSFcnParam(S, 1)
#define PARAM_DEF2(S)                  ssGetSFcnParam(S, 2)
#define PARAM_DEF3(S)                  ssGetSFcnParam(S, 3)
#define PARAM_DEF4(S)                  ssGetSFcnParam(S, 4)
#define PARAM_DEF5(S)                  ssGetSFcnParam(S, 5)
#define PARAM_DEF6(S)                  ssGetSFcnParam(S, 6)
#define PARAM_DEF7(S)                  ssGetSFcnParam(S, 7)
#define PARAM_DEF8(S)                  ssGetSFcnParam(S, 8)
#define PARAM_DEF9(S)                  ssGetSFcnParam(S, 9)
#define PARAM_DEF10(S)                 ssGetSFcnParam(S, 10)
#define PARAM_DEF11(S)                 ssGetSFcnParam(S, 11)
#define PARAM_DEF12(S)                 ssGetSFcnParam(S, 12)
#define PARAM_DEF13(S)                 ssGetSFcnParam(S, 13)
#define PARAM_DEF14(S)                 ssGetSFcnParam(S, 14)
#define IS_PARAM_BOOLEAN(pVal)         (mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal))
#define IS_PARAM_SINGLE(pVal)          (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsSingle(pVal))

extern void dspc_pid_Start_wrapper(const real32_T *Ts, const int_T p_width0,
  const real32_T *Kp, const int_T p_width1,
  const real32_T *Ki, const int_T p_width2,
  const real32_T *Kd, const int_T p_width3,
  const real32_T *N, const int_T p_width4,
  const boolean_T *limit_output, const int_T p_width5,
  const real32_T *upper_limit, const int_T p_width6,
  const real32_T *lower_limit, const int_T p_width7,
  const boolean_T *limit_rate, const int_T p_width8,
  const real32_T *rising_slew_rate, const int_T p_width9,
  const real32_T *falling_slew_rate, const int_T p_width10,
  const boolean_T *anti_windup_enabled, const int_T p_width11,
  const real32_T *Kb, const int_T p_width12,
  const boolean_T *tracking_enabled, const int_T p_width13,
  const real32_T *Kt, const int_T p_width14);
extern void dspc_pid_Outputs_wrapper(const real32_T *u,
  real32_T *y,
  real32_T *pidsum,
  real32_T *Xi,
  const real32_T *Ts, const int_T p_width0,
  const real32_T *Kp, const int_T p_width1,
  const real32_T *Ki, const int_T p_width2,
  const real32_T *Kd, const int_T p_width3,
  const real32_T *N, const int_T p_width4,
  const boolean_T *limit_output, const int_T p_width5,
  const real32_T *upper_limit, const int_T p_width6,
  const real32_T *lower_limit, const int_T p_width7,
  const boolean_T *limit_rate, const int_T p_width8,
  const real32_T *rising_slew_rate, const int_T p_width9,
  const real32_T *falling_slew_rate, const int_T p_width10,
  const boolean_T *anti_windup_enabled, const int_T p_width11,
  const real32_T *Kb, const int_T p_width12,
  const boolean_T *tracking_enabled, const int_T p_width13,
  const real32_T *Kt, const int_T p_width14);
extern void dspc_pid_Terminate_wrapper(const real32_T *Ts, const int_T p_width0,
  const real32_T *Kp, const int_T p_width1,
  const real32_T *Ki, const int_T p_width2,
  const real32_T *Kd, const int_T p_width3,
  const real32_T *N, const int_T p_width4,
  const boolean_T *limit_output, const int_T p_width5,
  const real32_T *upper_limit, const int_T p_width6,
  const real32_T *lower_limit, const int_T p_width7,
  const boolean_T *limit_rate, const int_T p_width8,
  const real32_T *rising_slew_rate, const int_T p_width9,
  const real32_T *falling_slew_rate, const int_T p_width10,
  const boolean_T *anti_windup_enabled, const int_T p_width11,
  const real32_T *Kb, const int_T p_width12,
  const boolean_T *tracking_enabled, const int_T p_width13,
  const real32_T *Kt, const int_T p_width14);

/*====================*
 * S-function methods *
 *====================*/
#define MDL_CHECK_PARAMETERS
#if defined(MDL_CHECK_PARAMETERS) && defined(MATLAB_MEX_FILE)

/* Function: mdlCheckParameters =============================================
 * Abstract:
 *     Verify parameter definitions and types.
 */
static void mdlCheckParameters(SimStruct *S)
{
  int paramIndex = 0;
  bool invalidParam = false;

  /* All parameters must match the S-function Builder Dialog */
  {
    const mxArray *pVal0 = ssGetSFcnParam(S, 0);
    if (!IS_PARAM_SINGLE(pVal0)) {
      invalidParam = true;
      paramIndex = 0;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal1 = ssGetSFcnParam(S, 1);
    if (!IS_PARAM_SINGLE(pVal1)) {
      invalidParam = true;
      paramIndex = 1;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal2 = ssGetSFcnParam(S, 2);
    if (!IS_PARAM_SINGLE(pVal2)) {
      invalidParam = true;
      paramIndex = 2;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal3 = ssGetSFcnParam(S, 3);
    if (!IS_PARAM_SINGLE(pVal3)) {
      invalidParam = true;
      paramIndex = 3;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal4 = ssGetSFcnParam(S, 4);
    if (!IS_PARAM_SINGLE(pVal4)) {
      invalidParam = true;
      paramIndex = 4;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal5 = ssGetSFcnParam(S, 5);
    if (!IS_PARAM_BOOLEAN(pVal5)) {
      invalidParam = true;
      paramIndex = 5;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal6 = ssGetSFcnParam(S, 6);
    if (!IS_PARAM_SINGLE(pVal6)) {
      invalidParam = true;
      paramIndex = 6;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal7 = ssGetSFcnParam(S, 7);
    if (!IS_PARAM_SINGLE(pVal7)) {
      invalidParam = true;
      paramIndex = 7;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal8 = ssGetSFcnParam(S, 8);
    if (!IS_PARAM_BOOLEAN(pVal8)) {
      invalidParam = true;
      paramIndex = 8;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal9 = ssGetSFcnParam(S, 9);
    if (!IS_PARAM_SINGLE(pVal9)) {
      invalidParam = true;
      paramIndex = 9;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal10 = ssGetSFcnParam(S, 10);
    if (!IS_PARAM_SINGLE(pVal10)) {
      invalidParam = true;
      paramIndex = 10;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal11 = ssGetSFcnParam(S, 11);
    if (!IS_PARAM_BOOLEAN(pVal11)) {
      invalidParam = true;
      paramIndex = 11;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal12 = ssGetSFcnParam(S, 12);
    if (!IS_PARAM_SINGLE(pVal12)) {
      invalidParam = true;
      paramIndex = 12;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal13 = ssGetSFcnParam(S, 13);
    if (!IS_PARAM_BOOLEAN(pVal13)) {
      invalidParam = true;
      paramIndex = 13;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal14 = ssGetSFcnParam(S, 14);
    if (!IS_PARAM_SINGLE(pVal14)) {
      invalidParam = true;
      paramIndex = 14;
      goto EXIT_POINT;
    }
  }

 EXIT_POINT:
  if (invalidParam) {
    static char parameterErrorMsg[1024];
    sprintf(parameterErrorMsg,
            "The data type and or complexity of parameter %d does not match the "
            "information specified in the S-function Builder dialog. "
            "For non-double parameters you will need to cast them using int8, int16, "
            "int32, uint8, uint16, uint32 or boolean.", paramIndex + 1);
    ssSetLocalErrorStatus(S, parameterErrorMsg);
  }

  return;
}

#endif                                 /* MDL_CHECK_PARAMETERS */

/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{
  DECL_AND_INIT_DIMSINFO(inputDimsInfo);
  DECL_AND_INIT_DIMSINFO(outputDimsInfo);
  ssSetNumSFcnParams(S, NPARAMS);      /* Number of expected parameters */

#if defined(MATLAB_MEX_FILE)

  if (ssGetNumSFcnParams(S) == ssGetSFcnParamsCount(S)) {
    mdlCheckParameters(S);
    if (ssGetErrorStatus(S) != NULL) {
      return;
    }
  } else {
    return;                            /* Parameter mismatch will be reported by Simulink */
  }

#endif

  ssSetArrayLayoutForCodeGen(S, SS_COLUMN_MAJOR);
  ssSetOperatingPointCompliance(S, USE_DEFAULT_OPERATING_POINT);
  ssSetNumContStates(S, NUM_CONT_STATES);
  ssSetNumDiscStates(S, NUM_DISC_STATES);
  if (!ssSetNumInputPorts(S, NUM_INPUTS))
    return;

  /* Input Port 0 */
  ssSetInputPortWidth(S, 0, INPUT_0_WIDTH);
  ssSetInputPortDataType(S, 0, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 0, 1);/*direct input signal access*/
  if (!ssSetNumOutputPorts(S, NUM_OUTPUTS))
    return;

  /* Output Port 0 */
  ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
  ssSetOutputPortDataType(S, 0, SS_SINGLE);
  ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);

  /* Output Port 1 */
  ssSetOutputPortWidth(S, 1, OUTPUT_1_WIDTH);
  ssSetOutputPortDataType(S, 1, SS_SINGLE);
  ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);

  /* Output Port 2 */
  ssSetOutputPortWidth(S, 2, OUTPUT_2_WIDTH);
  ssSetOutputPortDataType(S, 2, SS_SINGLE);
  ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);
  ssSetNumPWork(S, 0);
  ssSetNumSampleTimes(S, 1);
  ssSetNumRWork(S, 0);
  ssSetNumIWork(S, 0);
  ssSetNumModes(S, 0);
  ssSetNumNonsampledZCs(S, 0);
  ssSetSimulinkVersionGeneratedIn(S, "10.4");

  /* Take care when specifying exception free code - see sfuntmpl_doc.c */
  ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                   SS_OPTION_WORKS_WITH_CODE_REUSE));
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
  ssSetSampleTime(S, 0, SAMPLE_TIME_0);
  ssSetModelReferenceSampleTimeDefaultInheritance(S);
  ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE

static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetInputPortDataType(S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE

static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES

static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType(S, 0, SS_DOUBLE);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

#define MDL_SET_WORK_WIDTHS
#if defined(MDL_SET_WORK_WIDTHS) && defined(MATLAB_MEX_FILE)

static void mdlSetWorkWidths(SimStruct *S)
{
  const char_T *rtParamNames[] = { "P1", "P2", "P3", "P4", "P5", "P6", "P7",
    "P8", "P9", "P10", "P11", "P12", "P13", "P14", "P15" };

  ssRegAllTunableParamsAsRunTimeParams(S, rtParamNames);
}

#endif

#define MDL_START                                                /* Change to #undef to remove function */
#if defined(MDL_START)

/* Function: mdlStart =======================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{
  const int_T p_width0 = mxGetNumberOfElements(PARAM_DEF0(S));
  const int_T p_width1 = mxGetNumberOfElements(PARAM_DEF1(S));
  const int_T p_width2 = mxGetNumberOfElements(PARAM_DEF2(S));
  const int_T p_width3 = mxGetNumberOfElements(PARAM_DEF3(S));
  const int_T p_width4 = mxGetNumberOfElements(PARAM_DEF4(S));
  const int_T p_width5 = mxGetNumberOfElements(PARAM_DEF5(S));
  const int_T p_width6 = mxGetNumberOfElements(PARAM_DEF6(S));
  const int_T p_width7 = mxGetNumberOfElements(PARAM_DEF7(S));
  const int_T p_width8 = mxGetNumberOfElements(PARAM_DEF8(S));
  const int_T p_width9 = mxGetNumberOfElements(PARAM_DEF9(S));
  const int_T p_width10 = mxGetNumberOfElements(PARAM_DEF10(S));
  const int_T p_width11 = mxGetNumberOfElements(PARAM_DEF11(S));
  const int_T p_width12 = mxGetNumberOfElements(PARAM_DEF12(S));
  const int_T p_width13 = mxGetNumberOfElements(PARAM_DEF13(S));
  const int_T p_width14 = mxGetNumberOfElements(PARAM_DEF14(S));
  const real32_T *Ts = (const real32_T *) mxGetData(PARAM_DEF0(S));
  const real32_T *Kp = (const real32_T *) mxGetData(PARAM_DEF1(S));
  const real32_T *Ki = (const real32_T *) mxGetData(PARAM_DEF2(S));
  const real32_T *Kd = (const real32_T *) mxGetData(PARAM_DEF3(S));
  const real32_T *N = (const real32_T *) mxGetData(PARAM_DEF4(S));
  const boolean_T *limit_output = (const boolean_T *) mxGetData(PARAM_DEF5(S));
  const real32_T *upper_limit = (const real32_T *) mxGetData(PARAM_DEF6(S));
  const real32_T *lower_limit = (const real32_T *) mxGetData(PARAM_DEF7(S));
  const boolean_T *limit_rate = (const boolean_T *) mxGetData(PARAM_DEF8(S));
  const real32_T *rising_slew_rate = (const real32_T *) mxGetData(PARAM_DEF9(S));
  const real32_T *falling_slew_rate = (const real32_T *) mxGetData(PARAM_DEF10(S));
  const boolean_T *anti_windup_enabled = (const boolean_T *) mxGetData
    (PARAM_DEF11(S));
  const real32_T *Kb = (const real32_T *) mxGetData(PARAM_DEF12(S));
  const boolean_T *tracking_enabled = (const boolean_T *) mxGetData(PARAM_DEF13
    (S));
  const real32_T *Kt = (const real32_T *) mxGetData(PARAM_DEF14(S));
  dspc_pid_Start_wrapper(Ts, p_width0, Kp, p_width1, Ki, p_width2, Kd, p_width3,
    N, p_width4, limit_output, p_width5, upper_limit, p_width6, lower_limit,
    p_width7, limit_rate, p_width8, rising_slew_rate, p_width9,
    falling_slew_rate, p_width10, anti_windup_enabled, p_width11, Kb, p_width12,
    tracking_enabled, p_width13, Kt, p_width14);
}

#endif                                 /*  MDL_START */

/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
  const real32_T *u = (real32_T *) ssGetInputPortRealSignal(S, 0);
  real32_T *y = (real32_T *) ssGetOutputPortRealSignal(S, 0);
  real32_T *pidsum = (real32_T *) ssGetOutputPortRealSignal(S, 1);
  real32_T *Xi = (real32_T *) ssGetOutputPortRealSignal(S, 2);
  const int_T p_width0 = mxGetNumberOfElements(PARAM_DEF0(S));
  const int_T p_width1 = mxGetNumberOfElements(PARAM_DEF1(S));
  const int_T p_width2 = mxGetNumberOfElements(PARAM_DEF2(S));
  const int_T p_width3 = mxGetNumberOfElements(PARAM_DEF3(S));
  const int_T p_width4 = mxGetNumberOfElements(PARAM_DEF4(S));
  const int_T p_width5 = mxGetNumberOfElements(PARAM_DEF5(S));
  const int_T p_width6 = mxGetNumberOfElements(PARAM_DEF6(S));
  const int_T p_width7 = mxGetNumberOfElements(PARAM_DEF7(S));
  const int_T p_width8 = mxGetNumberOfElements(PARAM_DEF8(S));
  const int_T p_width9 = mxGetNumberOfElements(PARAM_DEF9(S));
  const int_T p_width10 = mxGetNumberOfElements(PARAM_DEF10(S));
  const int_T p_width11 = mxGetNumberOfElements(PARAM_DEF11(S));
  const int_T p_width12 = mxGetNumberOfElements(PARAM_DEF12(S));
  const int_T p_width13 = mxGetNumberOfElements(PARAM_DEF13(S));
  const int_T p_width14 = mxGetNumberOfElements(PARAM_DEF14(S));
  const real32_T *Ts = (const real32_T *) mxGetData(PARAM_DEF0(S));
  const real32_T *Kp = (const real32_T *) mxGetData(PARAM_DEF1(S));
  const real32_T *Ki = (const real32_T *) mxGetData(PARAM_DEF2(S));
  const real32_T *Kd = (const real32_T *) mxGetData(PARAM_DEF3(S));
  const real32_T *N = (const real32_T *) mxGetData(PARAM_DEF4(S));
  const boolean_T *limit_output = (const boolean_T *) mxGetData(PARAM_DEF5(S));
  const real32_T *upper_limit = (const real32_T *) mxGetData(PARAM_DEF6(S));
  const real32_T *lower_limit = (const real32_T *) mxGetData(PARAM_DEF7(S));
  const boolean_T *limit_rate = (const boolean_T *) mxGetData(PARAM_DEF8(S));
  const real32_T *rising_slew_rate = (const real32_T *) mxGetData(PARAM_DEF9(S));
  const real32_T *falling_slew_rate = (const real32_T *) mxGetData(PARAM_DEF10(S));
  const boolean_T *anti_windup_enabled = (const boolean_T *) mxGetData
    (PARAM_DEF11(S));
  const real32_T *Kb = (const real32_T *) mxGetData(PARAM_DEF12(S));
  const boolean_T *tracking_enabled = (const boolean_T *) mxGetData(PARAM_DEF13
    (S));
  const real32_T *Kt = (const real32_T *) mxGetData(PARAM_DEF14(S));
  dspc_pid_Outputs_wrapper(u, y, pidsum, Xi, Ts, p_width0, Kp, p_width1, Ki,
    p_width2, Kd, p_width3, N, p_width4, limit_output, p_width5, upper_limit,
    p_width6, lower_limit, p_width7, limit_rate, p_width8, rising_slew_rate,
    p_width9, falling_slew_rate, p_width10, anti_windup_enabled, p_width11, Kb,
    p_width12, tracking_enabled, p_width13, Kt, p_width14);
}

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
  const int_T p_width0 = mxGetNumberOfElements(PARAM_DEF0(S));
  const int_T p_width1 = mxGetNumberOfElements(PARAM_DEF1(S));
  const int_T p_width2 = mxGetNumberOfElements(PARAM_DEF2(S));
  const int_T p_width3 = mxGetNumberOfElements(PARAM_DEF3(S));
  const int_T p_width4 = mxGetNumberOfElements(PARAM_DEF4(S));
  const int_T p_width5 = mxGetNumberOfElements(PARAM_DEF5(S));
  const int_T p_width6 = mxGetNumberOfElements(PARAM_DEF6(S));
  const int_T p_width7 = mxGetNumberOfElements(PARAM_DEF7(S));
  const int_T p_width8 = mxGetNumberOfElements(PARAM_DEF8(S));
  const int_T p_width9 = mxGetNumberOfElements(PARAM_DEF9(S));
  const int_T p_width10 = mxGetNumberOfElements(PARAM_DEF10(S));
  const int_T p_width11 = mxGetNumberOfElements(PARAM_DEF11(S));
  const int_T p_width12 = mxGetNumberOfElements(PARAM_DEF12(S));
  const int_T p_width13 = mxGetNumberOfElements(PARAM_DEF13(S));
  const int_T p_width14 = mxGetNumberOfElements(PARAM_DEF14(S));
  const real32_T *Ts = (const real32_T *) mxGetData(PARAM_DEF0(S));
  const real32_T *Kp = (const real32_T *) mxGetData(PARAM_DEF1(S));
  const real32_T *Ki = (const real32_T *) mxGetData(PARAM_DEF2(S));
  const real32_T *Kd = (const real32_T *) mxGetData(PARAM_DEF3(S));
  const real32_T *N = (const real32_T *) mxGetData(PARAM_DEF4(S));
  const boolean_T *limit_output = (const boolean_T *) mxGetData(PARAM_DEF5(S));
  const real32_T *upper_limit = (const real32_T *) mxGetData(PARAM_DEF6(S));
  const real32_T *lower_limit = (const real32_T *) mxGetData(PARAM_DEF7(S));
  const boolean_T *limit_rate = (const boolean_T *) mxGetData(PARAM_DEF8(S));
  const real32_T *rising_slew_rate = (const real32_T *) mxGetData(PARAM_DEF9(S));
  const real32_T *falling_slew_rate = (const real32_T *) mxGetData(PARAM_DEF10(S));
  const boolean_T *anti_windup_enabled = (const boolean_T *) mxGetData
    (PARAM_DEF11(S));
  const real32_T *Kb = (const real32_T *) mxGetData(PARAM_DEF12(S));
  const boolean_T *tracking_enabled = (const boolean_T *) mxGetData(PARAM_DEF13
    (S));
  const real32_T *Kt = (const real32_T *) mxGetData(PARAM_DEF14(S));
  dspc_pid_Terminate_wrapper(Ts, p_width0, Kp, p_width1, Ki, p_width2, Kd,
    p_width3, N, p_width4, limit_output, p_width5, upper_limit, p_width6,
    lower_limit, p_width7, limit_rate, p_width8, rising_slew_rate, p_width9,
    falling_slew_rate, p_width10, anti_windup_enabled, p_width11, Kb, p_width12,
    tracking_enabled, p_width13, Kt, p_width14);
}

#ifdef MATLAB_MEX_FILE                 /* Is this file being compiled as a MEX-file? */
#include "simulink.c"                  /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"                   /* Code generation registration function */
#endif
